### ISSUE TITLE
Can you upgrade to 3.8.0?

### ISSUE THREAD

**Issue by JayLi1209** [sleighzy/ansible-kafka#45]
Thank you so much! This will make the cloud computing school assignment way easier. If time is not allowed, that's totally fine!

**Comment by sleighzy** [comment]
Hi @JayLi1209 . Apologies for the delay in responding, hopefully not too late for the school assignment. I'll look to make the changes in the next day or two.

**Comment by sleighzy** [comment]
Hi @JayLi1209 . I've discovered during testing that there is a known issue in Kafka 3.8.0 that can effect some systems and prevent Kafka (and other things like the console producer and consumer) from running. There is a workaround, but I'd prefer to wait till they release the upcoming fix for this first.

If you are unable to wait for this release then I can provide info on how to provide an Ansible variable to the playbook for this role so that it installs the 3.8.0 version, as well as the required work around.

**Comment by JayLi1209** [comment]
Hey @sleighzy, no worries! I have done all the configurations manually already. Thanks for the help and yes, you can wait until the fix is released.

**Comment by JayLi1209** [comment]
I will leave this issue open if you want to work on it at some point!

**Comment by sleighzy** [comment]
Kafka 3.8.1 was recently released with the fix I was after. I have now released a later version of this Ansible role (v3.3.0) containing this.

#47

**Comment by sleighzy** [comment]
@JayLi1209 , latest release is now available for you.
